"""Output files: naming, atomic writes, metadata."""

import os
import tempfile
from datetime import datetime
from pathlib import Path

from otr_replay import __version__
from otr_replay.models import ReplayError, Report

DISCLAIMER = (
    "This file is a reproduction generated by otr-replay. " "It is not an official o!TR record."
)
ATTRIBUTION = "osu! Tournament Rating (o!TR) — https://otr.stagec.net/"
DATASET_TERMS = "https://data.otr.stagec.net/"


def output_paths(
    instant: datetime, snapshot: datetime, tag: str, directory: Path
) -> tuple[Path, Path]:
    stem = (
        f"otr-replay_asof-{instant:%Y%m%dT%H%M%SZ}"
        f"_snapshot-{snapshot:%Y%m%dT%H%M%SZ}_processor-{tag}"
    )
    return directory / f"{stem}.csv", directory / f"{stem}.metadata.json"


def claim(*paths: Path) -> None:
    """Reserve output paths up front, refusing to overwrite existing files."""
    claimed: list[Path] = []
    for path in paths:
        try:
            path.touch(exist_ok=False)
        except FileExistsError:
            for done in claimed:
                done.unlink(missing_ok=True)
            raise ReplayError(
                "output",
                f"{path} already exists",
                "Move or rename the existing file and rerun.",
            ) from None
        claimed.append(path)


def write_atomic(path: Path, data: str) -> None:
    handle, tmp = tempfile.mkstemp(dir=path.parent, prefix=f".{path.name}.")
    try:
        with os.fdopen(handle, "w") as file:
            file.write(data)
        os.replace(tmp, path)
    finally:
        if os.path.exists(tmp):
            os.unlink(tmp)


def build_metadata(report: Report) -> dict:
    return {
        "application": "otr-replay",
        "application_version": __version__,
        "disclaimer": DISCLAIMER,
        "requested_at": _utc(report.requested_at),
        "effective_instant": _utc(report.instant),
        "replica": {
            "filename": report.replica.ref.name,
            "url": report.replica.ref.url,
            "timestamp": _utc(report.replica.ref.timestamp),
            "sha256": report.replica.sha256,
        },
        "processor": {
            "release": report.release.tag,
            "github_published_at": _utc(report.release.published_at),
            "image_pushed_at": _utc(report.release.pushed_at),
            "image": report.release.image,
        },
        "reconciliation": {
            "horizon": _utc(report.instant),
            "ratings_restored": report.reconciliation.ratings_restored,
            "adjustments_rolled_back": report.reconciliation.adjustments_rolled_back,
        },
        "output": {"csv": report.csv_path.name, "rows": report.row_count},
        "execution": {
            "started_at": _utc(report.started_at),
            "ended_at": _utc(report.finished_at),
        },
        "attribution": ATTRIBUTION,
        "dataset_terms": DATASET_TERMS,
    }


def _utc(value: datetime) -> str:
    return f"{value:%Y-%m-%dT%H:%M:%SZ}"
